## Docker compose file for base .NET Core backend container
## written by Nick Settoon 
## sourced from https://youtu.be/lcaDDxJv260?t=3071

version: '3.9'
services:
  backend:
    build: .
    ports: 
    - "8080:80"
    - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
    - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
    - ${HOME}/.aspnet/https:/root/.aspnet/https/
    - ${GDIR}/${REPO_NAME}:/app
  # db:
  #   image: "postgres:13.1-alpine"