## Docker compose file for base .NET Core backend container
## written by Nick Settoon 
## sourced from https://youtu.be/lcaDDxJv260?t=3071

version: '3.9'
services:
  sql_server: # service for SQL Server container
    image: "mcr.microsoft.com/mssql/server:2019-CU9-ubuntu-16.04"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "nickisawesome@1"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    profiles: ["support"]

  backend_dev:
    build:
      context: ./Backend
      dockerfile: ./Dockerfile
    ports: 
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
      DBServer: "sql_server"
      DBPort: "1433"
      Database: "Dowling"
      # !!!!!WARNING!!!!!
      # CHANGE DBUser and DBPassword FOR PRODUCTION ENV
      # NEVER DO THIS FOR PRODUCTION
      # I REPEAT NEVER DO THIS FOR PRODUCTION
      # I will take care of this later
      DBUser: "SA"
      DBPassword: "nickisawesome@1"

    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
      # PROJ_DIR = Backend project directory
      # - ${GDIR}/${PROJ_DIR}:/app
    depends_on:
      - sql_server
    profiles: ["dev"]

  backend_ci:
    build:
      context: ./Backend
      dockerfile: ./Dockerfile.rt
    ports: 
    - "8080:80"
    - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
    - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
    - ${HOME}/.aspnet/https:/root/.aspnet/https/
    # depends_on:
      # - DB
    profiles: ["ci"]
