## Docker file for base .NET Core backend container
## sourced from https://docs.docker.com/engine/examples/dotnetcore/

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out
# ENTRYPOINT [ "dotnet", "watch", "run", "/app/Backend.csproj", "/property:GenerateFullPaths=true", "/consoleloggerparameters:NoSummary" ]
ENTRYPOINT [ "dotnet", " out/Backend.dll" ]